"""empty message

Revision ID: a1a6792a194a
Revises: 
Create Date: 2022-12-05 17:16:49.639781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a6792a194a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deck',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pokemon', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('caption', sa.String(length=300), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('base_hp', sa.Integer(), nullable=True),
    sa.Column('base_att', sa.Integer(), nullable=True),
    sa.Column('base_def', sa.Integer(), nullable=True),
    sa.Column('base_spec_att', sa.Integer(), nullable=True),
    sa.Column('base_spec_def', sa.Integer(), nullable=True),
    sa.Column('base_speed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_table('user')
    op.drop_table('deck')
    # ### end Alembic commands ###
